= Cobalf JavaScript Library

[source]
----
_________         ___.            .__    _____  
\_   ___ \   ____ \_ |__  _____   |  | _/ ____\ 
/    \  \/  /  _ \ | __ \ \__  \  |  | \   __\  
\     \____(  <_> )| \_\ \ / __ \_|  |__|  |    
 \______  / \____/ |___  /(____  /|____/|__|    
        \/             \/      \/               
                                                                                              
----

Cobalf is a lightweight, fast, and feature-rich JavaScript framework aimed at simplifying front-end development tasks. It provides a comprehensive set of functionalities to empower developers in creating dynamic and secure web applications.

== Installation

To start using Cobalf in your project, you can include it via the CDN link:

[source,javascript]
----
<script src="https://cdn.jsdelivr.net/gh/simplyYan/cobalf@main/cobalf.js"></script>
----

== Docs
Documentation available on Wiki. Check it out: https://github.com/simplyYan/cobalf/wiki/Cobalf

== Features

Cobalf offers a plethora of features to streamline your front-end development:

* Lightweight: Cobalf was designed to be lightweight. Our framework was created end-to-end with pure JavaScript, no external libraries.
* Easy: Things don't have to be complicated. Even more so, in this day and age, they need to be uncomplicated. Front-end frameworks are difficult and tiring, with a steep learning curve. This issue influenced me and led me to create Cobalf. It's extremely easy and works in an obvious way.
* Open-source: Cobalf is open-source and anyone can contribute.
* Fast: Because it's lightweight and built only with JavaScript, Cobalf is lightweight. It's also built in a single file.
* Plug and Play: Simply add the JavaScript from the CDN or download it, and you're done. Why configurations? Why have a different file extension? Cobalf does the simple thing, which is why it's superior to all frameworks.
* Comprehensive documentation: Cobalf has incredible documentation! With easy-to-understand examples and explanations, it explains everything you need to know.
* Comprehensive: The word "front-end" is just a summary of Cobalf. In addition to dynamic HTML and CSS injection, string selection, declarative rendering, external JavaScript and dynamic CSS loading, dynamic tag editing, string comparison and string parsing, Cobalf offers request issuing (GET or POST). Our request emitter was built purely with JavaScript, without using third-party libraries or frameworks.
* Ideal for any project: Cobalf is perfect for any project.

== License

Cobalf is distributed under the BSD-3-Clause license. Refer to the [LICENSE](LICENSE) file for detailed information.

== Contributing

We welcome contributions from the community to enhance and improve Cobalf. To contribute, please fork this repository, make your changes, and submit a pull request. Your feedback and contributions are highly appreciated!

Thank you for choosing Cobalf for your front-end development needs!
