= Cobalf JavaScript Library

[source]
----
_________         ___.            .__    __    
\_   ___ \   ____ \_ |__  _____   |  | _/  |_  
/    \  \/  /  _ \ | __ \ \__  \  |  | \   __\ 
\     \____(  <_> )| \_\ \ / __ \_|  |__|  |   
 \______  / \____/ |___  /(____  /|____/|__|   
        \/             \/      \/              
                                               
----

Cobalf is a lightweight, fast, and feature-rich JavaScript library aimed at simplifying front-end development tasks. It provides a comprehensive set of functionalities to empower developers in creating dynamic and secure web applications.

== Installation

To start using Cobalf in your project, you can include it via the CDN link:

[source,javascript]
----
<script src="https://cdn.jsdelivr.net/gh/simplyYan/cobalf@main/cobalf.js"></script>
----

== Docs
Documentation available on Wiki. Check it out: https://github.com/simplyYan/cobalf/wiki/Cobalf

== Features

Cobalf offers a plethora of features to streamline your front-end development:

* HTML Manipulation: Easily add, modify, and sanitize HTML content in the document.
* LocalStorage Handling: Store and retrieve encrypted data securely in the browser's localStorage.
* Network Requests: Perform AJAX requests with ease and handle responses seamlessly.
* Toolbox Activation: Access useful tools like current date, last modification time, etc.
* Encryption & Decryption: Simulate encryption and decryption methods for data security.
* Lightweight & Fast: Designed to be efficient and performant for optimal user experience.
* Open-Source & Comprehensive Documentation: Transparent source code and extensive documentation for easy usage and understanding.

== License

Cobalf is distributed under the BSD-3-Clause license. Refer to the [LICENSE](LICENSE) file for detailed information.

== Contributing

We welcome contributions from the community to enhance and improve Cobalf. To contribute, please fork this repository, make your changes, and submit a pull request. Your feedback and contributions are highly appreciated!

Thank you for choosing Cobalf for your front-end development needs!
